# configuration file of Typor


set(TYPOR_CONFIG_SUPPORTED_BACKEND "SQLITE")

foreach (BACKEND IN LISTS TYPOR_CONFIG_SUPPORTED_BACKEND)
	option(TYPOR_CONFIG_BUILD_${BACKEND}_BACKEND OFF)
endforeach()

#set(TYPOR_CONFIG_CXX_STANDARD cxx_std_26)
set_property(GLOBAL PROPERTY CXX_STANDARD 26)
set_property(GLOBAL PROPERTY CXX_STANDARD_REQUIRED ON)
